### ISSUE TITLE
Verify potential impacts from IFA, DFA and EFA

### ISSUE THREAD

**Issue by 22388o** [BitSwap-BiFi/Bitswap-core#181]
[RGB20](https://github.com/RGB-WG/rgb-schemata/issues/20)

**Comment by 22388o** [comment]
**Potential impacts**

 - IFA: The contract ID can change or hold "original contract"
 - DFA: The contract ID can change like IFA, but the operations can change
 - EFA: Edit assets nominal can impact exist contracts on DEX

**Comment by Rsync25** [comment]
Well done!
